[workspace]
members = ["crates/boya_core", "crates/boya_wasm"]
resolver = "3"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
boya_core = { path = "./crates/boya_core" }
