name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install fasmarm
        run: |
          curl https://arm.flatassembler.net/FASMARM_full.ZIP -o fasmarm.zip
          unzip fasmarm.zip -d fasmarm
          sudo chmod +x fasmarm/fasmarm.x64
          sudo cp fasmarm/fasmarm.x64 /usr/local/bin/fasmarm

      - name: Initialize submodules
        run: git submodule update --init

      - name: Download BIOS
        run: curl https://github.com/ez-me/gba-bios/releases/download/1.0/gba_bios.bin -LO

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --workspace --lib --verbose

      - name: Lint
        run: cargo clippy -- -D warnings
